/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ExercisesRouteImport } from './routes/exercises'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkoutsIndexRouteImport } from './routes/workouts.index'
import { Route as WorkoutsNewRouteImport } from './routes/workouts.new'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoStorybookRouteImport } from './routes/demo/storybook'
import { Route as DemoStoreRouteImport } from './routes/demo/store'
import { Route as DemoPrismaRouteImport } from './routes/demo/prisma'
import { Route as DemoNeonRouteImport } from './routes/demo/neon'
import { Route as DemoMcpTodosRouteImport } from './routes/demo/mcp-todos'
import { Route as DemoDbChatApiRouteImport } from './routes/demo/db-chat-api'
import { Route as DemoDbChatRouteImport } from './routes/demo/db-chat'
import { Route as DemoClerkRouteImport } from './routes/demo/clerk'
import { Route as DemoSentryTestingRouteImport } from './routes/demo/sentry.testing'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'
import { Route as DemoApiMcpTodosRouteImport } from './routes/demo/api.mcp-todos'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesRoute = ExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsIndexRoute = WorkoutsIndexRouteImport.update({
  id: '/workouts/',
  path: '/workouts/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsNewRoute = WorkoutsNewRouteImport.update({
  id: '/workouts/new',
  path: '/workouts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStorybookRoute = DemoStorybookRouteImport.update({
  id: '/demo/storybook',
  path: '/demo/storybook',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStoreRoute = DemoStoreRouteImport.update({
  id: '/demo/store',
  path: '/demo/store',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPrismaRoute = DemoPrismaRouteImport.update({
  id: '/demo/prisma',
  path: '/demo/prisma',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoNeonRoute = DemoNeonRouteImport.update({
  id: '/demo/neon',
  path: '/demo/neon',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoMcpTodosRoute = DemoMcpTodosRouteImport.update({
  id: '/demo/mcp-todos',
  path: '/demo/mcp-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDbChatApiRoute = DemoDbChatApiRouteImport.update({
  id: '/demo/db-chat-api',
  path: '/demo/db-chat-api',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDbChatRoute = DemoDbChatRouteImport.update({
  id: '/demo/db-chat',
  path: '/demo/db-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoClerkRoute = DemoClerkRouteImport.update({
  id: '/demo/clerk',
  path: '/demo/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoSentryTestingRoute = DemoSentryTestingRouteImport.update({
  id: '/demo/sentry/testing',
  path: '/demo/sentry/testing',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiMcpTodosRoute = DemoApiMcpTodosRouteImport.update({
  id: '/demo/api/mcp-todos',
  path: '/demo/api/mcp-todos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/exercises': typeof ExercisesRoute
  '/mcp': typeof McpRoute
  '/profile': typeof ProfileRoute
  '/demo/clerk': typeof DemoClerkRoute
  '/demo/db-chat': typeof DemoDbChatRoute
  '/demo/db-chat-api': typeof DemoDbChatApiRoute
  '/demo/mcp-todos': typeof DemoMcpTodosRoute
  '/demo/neon': typeof DemoNeonRoute
  '/demo/prisma': typeof DemoPrismaRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/storybook': typeof DemoStorybookRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/workouts/new': typeof WorkoutsNewRoute
  '/workouts/': typeof WorkoutsIndexRoute
  '/demo/api/mcp-todos': typeof DemoApiMcpTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/sentry/testing': typeof DemoSentryTestingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/exercises': typeof ExercisesRoute
  '/mcp': typeof McpRoute
  '/profile': typeof ProfileRoute
  '/demo/clerk': typeof DemoClerkRoute
  '/demo/db-chat': typeof DemoDbChatRoute
  '/demo/db-chat-api': typeof DemoDbChatApiRoute
  '/demo/mcp-todos': typeof DemoMcpTodosRoute
  '/demo/neon': typeof DemoNeonRoute
  '/demo/prisma': typeof DemoPrismaRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/storybook': typeof DemoStorybookRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/workouts/new': typeof WorkoutsNewRoute
  '/workouts': typeof WorkoutsIndexRoute
  '/demo/api/mcp-todos': typeof DemoApiMcpTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/sentry/testing': typeof DemoSentryTestingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/exercises': typeof ExercisesRoute
  '/mcp': typeof McpRoute
  '/profile': typeof ProfileRoute
  '/demo/clerk': typeof DemoClerkRoute
  '/demo/db-chat': typeof DemoDbChatRoute
  '/demo/db-chat-api': typeof DemoDbChatApiRoute
  '/demo/mcp-todos': typeof DemoMcpTodosRoute
  '/demo/neon': typeof DemoNeonRoute
  '/demo/prisma': typeof DemoPrismaRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/storybook': typeof DemoStorybookRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/workouts/new': typeof WorkoutsNewRoute
  '/workouts/': typeof WorkoutsIndexRoute
  '/demo/api/mcp-todos': typeof DemoApiMcpTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/sentry/testing': typeof DemoSentryTestingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/exercises'
    | '/mcp'
    | '/profile'
    | '/demo/clerk'
    | '/demo/db-chat'
    | '/demo/db-chat-api'
    | '/demo/mcp-todos'
    | '/demo/neon'
    | '/demo/prisma'
    | '/demo/store'
    | '/demo/storybook'
    | '/demo/tanstack-query'
    | '/workouts/new'
    | '/workouts/'
    | '/demo/api/mcp-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/sentry/testing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/exercises'
    | '/mcp'
    | '/profile'
    | '/demo/clerk'
    | '/demo/db-chat'
    | '/demo/db-chat-api'
    | '/demo/mcp-todos'
    | '/demo/neon'
    | '/demo/prisma'
    | '/demo/store'
    | '/demo/storybook'
    | '/demo/tanstack-query'
    | '/workouts/new'
    | '/workouts'
    | '/demo/api/mcp-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/sentry/testing'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/exercises'
    | '/mcp'
    | '/profile'
    | '/demo/clerk'
    | '/demo/db-chat'
    | '/demo/db-chat-api'
    | '/demo/mcp-todos'
    | '/demo/neon'
    | '/demo/prisma'
    | '/demo/store'
    | '/demo/storybook'
    | '/demo/tanstack-query'
    | '/workouts/new'
    | '/workouts/'
    | '/demo/api/mcp-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/sentry/testing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ExercisesRoute: typeof ExercisesRoute
  McpRoute: typeof McpRoute
  ProfileRoute: typeof ProfileRoute
  DemoClerkRoute: typeof DemoClerkRoute
  DemoDbChatRoute: typeof DemoDbChatRoute
  DemoDbChatApiRoute: typeof DemoDbChatApiRoute
  DemoMcpTodosRoute: typeof DemoMcpTodosRoute
  DemoNeonRoute: typeof DemoNeonRoute
  DemoPrismaRoute: typeof DemoPrismaRoute
  DemoStoreRoute: typeof DemoStoreRoute
  DemoStorybookRoute: typeof DemoStorybookRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  WorkoutsNewRoute: typeof WorkoutsNewRoute
  WorkoutsIndexRoute: typeof WorkoutsIndexRoute
  DemoApiMcpTodosRoute: typeof DemoApiMcpTodosRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
  DemoSentryTestingRoute: typeof DemoSentryTestingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises': {
      id: '/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof ExercisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts/': {
      id: '/workouts/'
      path: '/workouts'
      fullPath: '/workouts/'
      preLoaderRoute: typeof WorkoutsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts/new': {
      id: '/workouts/new'
      path: '/workouts/new'
      fullPath: '/workouts/new'
      preLoaderRoute: typeof WorkoutsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/storybook': {
      id: '/demo/storybook'
      path: '/demo/storybook'
      fullPath: '/demo/storybook'
      preLoaderRoute: typeof DemoStorybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/store': {
      id: '/demo/store'
      path: '/demo/store'
      fullPath: '/demo/store'
      preLoaderRoute: typeof DemoStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/prisma': {
      id: '/demo/prisma'
      path: '/demo/prisma'
      fullPath: '/demo/prisma'
      preLoaderRoute: typeof DemoPrismaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/neon': {
      id: '/demo/neon'
      path: '/demo/neon'
      fullPath: '/demo/neon'
      preLoaderRoute: typeof DemoNeonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/mcp-todos': {
      id: '/demo/mcp-todos'
      path: '/demo/mcp-todos'
      fullPath: '/demo/mcp-todos'
      preLoaderRoute: typeof DemoMcpTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/db-chat-api': {
      id: '/demo/db-chat-api'
      path: '/demo/db-chat-api'
      fullPath: '/demo/db-chat-api'
      preLoaderRoute: typeof DemoDbChatApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/db-chat': {
      id: '/demo/db-chat'
      path: '/demo/db-chat'
      fullPath: '/demo/db-chat'
      preLoaderRoute: typeof DemoDbChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/clerk': {
      id: '/demo/clerk'
      path: '/demo/clerk'
      fullPath: '/demo/clerk'
      preLoaderRoute: typeof DemoClerkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/sentry/testing': {
      id: '/demo/sentry/testing'
      path: '/demo/sentry/testing'
      fullPath: '/demo/sentry/testing'
      preLoaderRoute: typeof DemoSentryTestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/mcp-todos': {
      id: '/demo/api/mcp-todos'
      path: '/demo/api/mcp-todos'
      fullPath: '/demo/api/mcp-todos'
      preLoaderRoute: typeof DemoApiMcpTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ExercisesRoute: ExercisesRoute,
  McpRoute: McpRoute,
  ProfileRoute: ProfileRoute,
  DemoClerkRoute: DemoClerkRoute,
  DemoDbChatRoute: DemoDbChatRoute,
  DemoDbChatApiRoute: DemoDbChatApiRoute,
  DemoMcpTodosRoute: DemoMcpTodosRoute,
  DemoNeonRoute: DemoNeonRoute,
  DemoPrismaRoute: DemoPrismaRoute,
  DemoStoreRoute: DemoStoreRoute,
  DemoStorybookRoute: DemoStorybookRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  WorkoutsNewRoute: WorkoutsNewRoute,
  WorkoutsIndexRoute: WorkoutsIndexRoute,
  DemoApiMcpTodosRoute: DemoApiMcpTodosRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
  DemoSentryTestingRoute: DemoSentryTestingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
